# version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: eparaw
      POSTGRES_PASSWORD: eparaw_password
      POSTGRES_DB: eparawdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eparaw-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - eparaw-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: eparaw
      RABBITMQ_DEFAULT_PASS: eparaw_password
    networks:
      - eparaw-network

  catalog.api:
    image: eparaw/catalog.api:latest
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=eparaw_catalog;Username=eparaw;Password=eparaw_password
      - EventBus__Connection=rabbitmq
    ports:
      - "5001:8080"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - eparaw-network

  ordering.api:
    image: eparaw/ordering.api:latest
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=eparaw_ordering;Username=eparaw;Password=eparaw_password
      - EventBus__Connection=rabbitmq
    ports:
      - "5002:8080"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - eparaw-network

  identity.api:
    image: eparaw/identity.api:latest
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=eparaw_identity;Username=eparaw;Password=eparaw_password
    ports:
      - "5003:8080"
    depends_on:
      - postgres
    networks:
      - eparaw-network

  web.bff:
    image: eparaw/web.bff:latest
    build:
      context: .
      dockerfile: src/ApiGateways/Web.BFF/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Catalog=http://catalog.api:8080
      - Services__Ordering=http://ordering.api:8080
      - Services__Identity=http://identity.api:8080
    ports:
      - "5000:8080"
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
    networks:
      - eparaw-network

volumes:
  postgres_data:

networks:
  eparaw-network:
    driver: bridge